apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: 2021-03-27T19:46:46Z
  labels:
    app: userapi
  name: userapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userapi
  strategy: {}
  template:
    metadata:
      creationTimestamp: 2021-03-27T19:46:46Z
      labels:
        app: userapi
    spec:
      containers:
      - image: cloudlearnall/statecode:1.1
        name: statecode
        resources: {}
status: {}
--- 
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2021-03-27T19:46:46Z
  labels:
    app: userapi
  name: userapi
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: userapi
  type: LoadBalancer
status:
  loadBalancer: {}
